### ISSUE TITLE
Choc spacing or mx spacing? Which keycaps to choose

### ISSUE THREAD

**Issue by TheAce4K** [JonMuller/gerbers#16]
Hi,

First off I just want to say, amazing work you have done here! I really like your design and would like to build it. However as im in the process of gathering all the parts I started wondering. Is the Corne choc Xiao board choc spaced or mx spaced. Because I know there are some mx spaced choc boards out there which leaves big ugly gaps between the keys unless you get slightly bigger keycaps.

So the question is really, what spacing are you using on the corne choc Xiao pcb board?

**Comment by JonMuller** [comment]
My apologies!! I could have sworn I answered this. 

This is absolutely Choc spacing. I should probably update the description. Only Choc caps will work on this board.

Thanks!

**Comment by TheAce4K** [comment]
Thank you for the response! Very appreciated
