### ISSUE TITLE
dongle mode

### ISSUE THREAD

**Issue by johnnytshi** [JonMuller/gerbers#19]
Hi Jon,

This is exactly what i was looking for, just place my order via jcpcb. Thanks for the amazing work.
I was curious if you have any experience with 3 xiao config: 1 as dongle, 1 for left, 1 for right

All the best!

Johnny

**Comment by JonMuller** [comment]
Hi Johnny,

I have not personally set up a keyboard with dongle mode, but there's no reason you shouldn't be able to. You should be able to get all the info you need to set it up from the files I provided. At the very least, it will have the GPIO I used for the matrix. I would think that's the most important stuff. 

I've been meaning to try out the new ZMK Studio stuff, so if I get around to a dongle set up too, I'll try and update here.
