### ISSUE TITLE
Other epaper support

### ISSUE THREAD

**Issue by j1n6** [JonMuller/gerbers#3]
Do you know if it is even possible to use the follow epaper-102 display on this board?  Thank you in advance!
https://github.com/Nicell/epaper-102
Here's the pin layout:

![Screenshot 2023-03-27 at 16 53 30](https://user-images.githubusercontent.com/37033/227995892-f2323315-c759-4d27-9992-e149a5e80d93.png)

**Comment by JonMuller** [comment]
It's not pin compatible, no. But I wouldn't say it's impossible. I believe it requires one more pin to be wired beyond what's already available. So there would be some extra bodging necessary. 

I have some of those boards and a few e-paper displays that I've tested with. If I'm being honest, the refresh rate is pretty frustrating. And the sharp memory displays are actually more power efficient. (Nice!View is a sharp memory display) so it's a tough sell for me. 

Those displays are definitely supported by ZMK and it can be done, so if you really wanted to, you absolutely could. I just have a hard time recommending it.

**Comment by JonMuller** [comment]
Not much else to say about this. Closing the issue.

**Comment by JonMuller** [comment]
closing.
